### PR TITLE
Configure SPI bus via Web Interface

### PR DESCRIPTION
**Pull request by nullstalgia**
I'm 99% sure I'm missing some parts, but this is just the barebones that I started with until I realized I can't finish it alone.

### CODE REVIEW

**Comment by sidoh** [comment]
From a backend perspective, this looks right.

Do we just want a VSPI/HSPI selector in the UI?  Anything else I'm missing?

**Comment by nullstalgia** [comment]
I think that's about it.

Since we can't set pins ourselves (at least, not without greatly modifying the e-paper lib), that's basically the only option we have. :man_shrugging: 

Since I started working on the project, I've been using the VSPI pins without issue (My ESP32-01 board, and even this dev board only have VSPI broken out properly)

**Comment by sidoh** [comment]
Cool.  Gonna wrap up the deep sleep changes and I'll take a look.

**Comment by nullstalgia** [comment]
Cheers. I'll make a small edit to the README about what pins are usable.

**Comment by nullstalgia** [comment]
One small note, the example picture I posted before has incorrect pin mappings. [Double check against this](https://github.com/loboris/Lua-RTOS-ESP32-lobo/wiki/ESP32-SPI-pins) if you are putting the pin numbers into the UI itself. (SPI2 == HSPI. SPI3 == VSPI.)

**Comment by sidoh** [comment]
Implemented the suggestions.  "System" card on dashboard shows number of seconds left in current awake cycle and has a button to cancel it:

image

Kicking off a firmware update should automatically cancel deep sleep, although that might not currently be reflected in the UI.

Let me know if it's working for you.

**Comment by sidoh** [comment]
Looks like it's working (in that I can save the VSPI setting and my display no longer works, lol).

Let me know if this does the trick for you?

setting preview:

image

**Comment by nullstalgia** [comment]
VSPI is working on my display! :+1:

**Comment by sidoh** [comment]
Great.  Thanks for your help with this one!

**Pull request merged**
