### PR TITLE
Descriptive display names in Web Interface

### PR DESCRIPTION
**Pull request by nullstalgia**
For issue #13.

Gonna be honest, I'm not the biggest fan of this kinda.. bruteforce-ish approach.

But from what I can see, it does work. (Make sure to reset the ESP after changing display type!)

---

Additionally, I noticed some displays were out of order or just missing in one form or another. That has been addressed. :)

### CODE REVIEW

**Comment by sidoh** [comment]
Awesome, thank you!  Thanks for catching the missing display types as well.

> Gonna be honest, I'm not the biggest fan of this kinda.. bruteforce-ish approach.

Do you mean to refer to what's already here, or the way you made the change?  In case it's the former -- I'm definitely open to ideas on how to better handle supporting multiple displays.  I toiled for a while trying to find a way that didn't involve a bunch of casing, but it felt like C++ was conspiring against me and I folded.

I had been imagining keeping the model numbers as the identifier and associating a display name with it, rather than putting the display name in with the model number.  Putting the display name in the ID will mean existing setups will revert to the default display name, which is obviously not ideal.

**Comment by nullstalgia** [comment]
Well at first I meant the way I did the change, but frankly both is accurate now that I think about it :laughing: 

And if I'm understanding correctly, you mean having it be like this

```html
<option value="GDEP015OC1">GDEP015OC1 (1.54" B/W)</option>
```
Where the internal value is the same, but just the outward name is different? I do agree that would be the best way to go about it, but I have no experience with React, if I'm being honest. 

Also, from what I could tell, the const chars that hold the names for all of the displays in 
[DisplayTypeHelpers.cpp](https://github.com/sidoh/epaper_templates/blob/master/lib/Display/DisplayTypeHelpers.cpp) is what the ESP reports back when looking at the current setting and when asking via the API with `/api/v1/screens`

image

So it's entirely possible the change could be done just in the Web assets, leaving the ESP32 code as is. (But leaving in the missing displays)

**Comment by sidoh** [comment]
> Well at first I meant the way I did the change, but frankly both is accurate now that I think about it 😆

Any ideas on how to improve it?  C++ is pretty far from my primary language, but I'm reasonably confident that there's not a way to solve this that doesn't involve listing all of the displays.  The forces playing against us here are (A) runtime metaprogramming in C++ isn't possible (or at least, I'm unaware of a way), and (B) GxEPD2 has no runtime registry of available drivers.

Only other path I can think of is code generation, which sounds significantly worse.

> And if I'm understanding correctly, you mean having it be like this
> 
>```html
> <option value="GDEP015OC1">GDEP015OC1 (1.54" B/W)</option>
>```
> 
> Where the internal value is the same, but just the outward name is different? I do agree that would be the best way to go about it, but I have no experience with React, if I'm being honest.

Yeah, precisely.  Implicit in that (and I think more importantly), the server-side code continues to key off of just the model ID.

If the approach sounds good to you, I can take a crack at it building on what you've got here.  Also happy to offer pointers on the React stuff. 

(btw - the fact that the list of models is hardcoded in both the server and the UI is a bit of a relic.  The `/api/v1/screens` route didn't exist until recently, when I needed to get the resolution of the screens for the WYSIWIG editor.  It should be possible to serve everything from the API now and avoid the duplication.  Not necessary for this change, just thought I'd mention.)

**Comment by nullstalgia** [comment]
C++ isn't my primary language either. I find myself much more comfortable in KiCad making PCBs, then have to drag myself over to the Arduino IDE/VSCode to make it function :P

I could ask a friend who is much more comfortable with C++ than I ever will be, but I agree it's unlikely to have an elegant solution like we want without code generation. (I have done that once, and while it worked, it's a pain to deal with outside of the 5 mins where it sounded like a good idea)

And feel free to throw in commits to the branch. I pretty much always allow contributors to edit my pulls, haven't had a reason not to yet.

**Comment by sidoh** [comment]
If your friend is open to offering his thoughts, sure, that sounds good.

Sounds good.  I should be able to look this weekend.

**Comment by nullstalgia** [comment]
Additionally, it would be good if we did add a link to either your fork or the original GxEPD2, since there's a set of displays that have very little difference except the name.

```
GDE0213B1 (2.13\" B/W)
GDEH0213B72 (2.13\" B/W)
GDEH0213B73 (2.13\" B/W)
GDEW0213I5F (2.13\" B/W FLEX)
```

**Comment by sidoh** [comment]
Fiddling around with getting the descriptions out of the UI schema, should have a patch shortly

**Comment by sidoh** [comment]
@nullstalgia, took a stab at what we talked about earlier in the week.  Looks like it works, and has the same visible effect:

image

Let me know if this looks good to you and we can merge.

(btw -- thanks for granting access to your branch/fork, made it much easier to collaborate :)

**Comment by nullstalgia** [comment]
Seems to work here as well!

And poking around the template editor to make sure no regressions sneaked in, it seems stable!

image

Should we have a link under the select to the repo to explain these very similar displays, or leave it as is?

**Comment by sidoh** [comment]
Not that it would hurt, I think we're probably OK without it for now.  Happy to merge a patch to the README/other docs if you think we should.

**Pull request merged**
